[window]
title = "raiden engine"
width = 800
height = 600
resizable = true
fullscreen = false
vsync = false

[render]
backend = "vulkan"
validation = true

[game.platform]
linux = "lib/libExampleGame.so"
